### ISSUE TITLE
Topic name for AWS IoT subscription

### ISSUE THREAD

**Issue by qraleq** [AxisCommunications/acap-integration-examples-aws#12]
Hi, 
I'm using https://github.com/AxisCommunications/acap-integration-examples-aws/tree/main/telemetry-to-aws-iot-core to connect an AXIS camera to AWS IoT. I managed to connect the camera to the cloud, but now I can't verify if MQTT messages are being delivered properly. There's this section in the instructions: "Proceed with viewing the events in AWS IoT Core in the AWS Console.", but I can't find the exact topic on which the camera is publishing the events. 

In the "MQTT events" section of the camera, it shows `Topic: onvif:UserAlarm/axis:Recurring/Pulse` as the topic, but I don't know exact topic in AWS that I should subscribe to.
 
Can you help me with this?

**Comment by qraleq** [comment]
Hi @mattias-kindborg-at-work, can you please help me with my question? I've spent some time trying to figure out the topic names, but there's not enough info that I found which could help me figure it out.
Thank you!

**Comment by mattias-kindborg-at-work** [comment]
Hi @qraleq and welcome! Let me first start by apologizing for the incredible late answer. This response time is not acceptable, and we will start to behave like mindful and responsible open source citizens. Again, my deepest appologizes and I promise to improve in the future, ensuring that issues like this aren't left unanswered.

I will add information to the `README` instructions, helping developers like you to know what to enter in the AWS Console to be able to view the events published from an Axis camera. I'll create a pull request and link it in this issue.

**Comment by mattias-kindborg-at-work** [comment]
@qraleq, I've added more detailed information regarding the MQTT test client in the AWS Console. Even though it didn't help you due to the long time from question to answer, I hope that other developers wondering about the MQTT topic will get help from it.

**Comment by qraleq** [comment]
Thank you for the help. I've already found ways to get what I needed :)
